#! /usr/bin/env bash
# SPDX-FileCopyrightText: © 2020 Chindraba (Ronald Lamoreaux) <code@chindraba.work>
# SPDX-License-Identifier: MIT

# Copyright © 2020  Chindraba (Ronald Lamoreaux)
# 
#     <upskill@chindraba.work>
# 
# — All Rights Reserved
# 
# The MIT License
#     
#     Permission is hereby granted, free of charge, to any person obtaining a
#     copy of this software and associated documentation files (the "Software"),
#     to deal in the Software without restriction, including without limitation
#     the rights to use, copy, modify, merge, publish, distribute, sublicense,
#     and/or sell copies of the Software, and to permit persons to whom the
#     Software is furnished to do so, subject to the following conditions:
# 
#     The above copyright notice and this permission notice shall be included
#     in all copies or substantial portions of the Software
# 
#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGE MENT. IN NO EVENT SHALL
#     THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#     LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#     FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#     DEALINGS IN THE SOFTWARE.

# Script to pre-build repos for lessons from the FEWD class.
# Up to 3 command arguments:
#   repo_name: the name applied to the repo, and the "project" name inside the
#       files for documentation
#   title: the title of the exercise/homework. Used as the <title> in the HTML
#       and in the README's [optional]
#   desc: A description of the project [optional]
# Will also use a pair of files <repo_name>.css and <repo_name>.sc for the CSS
# and Starter code, respectively, supplied by the instructor. If the file is not
# found, a placehold text is added.

repo_name="$1"
title="${2:-Lesson x: Activity: Name}"
desc="${3:-Description of the project from the slide goes here.}"
cp -r ga-template "${repo_name}"
[ -e "${repo_name}.sc" ] || echo "    STARTER CODE goes here." > "${repo_name}.sc"
[ -e "${repo_name}.css" ] || echo "    STARTER CSS goes here." > "${repo_name}.css"
for target_file in README.md README.txt CONTRIBUTING.md CONTRIBUTING.txt project_page.html .git/config; do
    target="${repo_name}/${target_file}"
    sed -i -e "s/<<PRJ>>/${repo_name}/g;s/<<TITLE>>/${title}/g;s/<<DESC>>/${desc}/g;" "${target}"
    # https://unix.stackexchange.com/a/317956/207673
    sed 's/<<STARTER_CSS>>/$x/g' ${target} | x="$(<${repo_name}.css)" envsubst '$x' > ${target}2
    sed 's/<<STARTER_CODE>>/$x/g' "${target}2" | x="$(<"${repo_name}.sc")" envsubst '$x' > "${target}"
    rm "${target}2"
done
